language: python
python:
  - '3.7'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

script:
  - python manage.py test core ersatz favorites products profiles signup users
  - python manage.py test functional_tests
