language: python
python:
  - '3.7'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=disquaire_project.settings.travis

script:
  - python manage.py test core ersatz favorites products profiles signup users
  - python manage.py test functional_tests
