# Generated by Django 2.2.4 on 2019-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='bottom_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='middle_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
