# Generated by Django 2.2.6 on 2019-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190910_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_places',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
